name: Build Green Packages (Win + Mac)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  PYTHON_VERSION: '3.11'
  # 关键：让 Playwright 把浏览器装到仓库目录 ./ms-playwright
  PLAYWRIGHT_BROWSERS_PATH: ./ms-playwright

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install deps (incl. PyInstaller) and Playwright browsers
        shell: pwsh
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pyinstaller
          python -m playwright install chromium

      - name: Build exe with PyInstaller
        shell: cmd
        run: >
          python -m pyinstaller -y --clean --windowed
          --add-data "ms-playwright;ms-playwright"
          --name "WebImageSaver" app.py

      - name: Zip artifact (Windows)
        shell: pwsh
        run: |
          Compress-Archive -Path dist\WebImageSaver\* -DestinationPath WebImageSaver-win64.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebImageSaver-win64.zip
          path: WebImageSaver-win64.zip

  build-mac-arm64:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install deps (incl. PyInstaller) and Playwright browsers
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pyinstaller
          python -m playwright install chromium

      - name: Build app with PyInstaller
        run: |
          python -m pyinstaller -y --clean --windowed \
            --add-data "ms-playwright:ms-playwright" \
            --name "WebImageSaver" app.py

      - name: Zip artifact (macOS arm64)
        run: |
          cd dist && zip -r ../WebImageSaver-mac-arm64.zip WebImageSaver.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebImageSaver-mac-arm64.zip
          path: WebImageSaver-mac-arm64.zip

  build-mac-x64:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install deps (incl. PyInstaller) and Playwright browsers
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pyinstaller
          python -m playwright install chromium

      - name: Build app with PyInstaller
        run: |
          python -m pyinstaller -y --clean --windowed \
            --add-data "ms-playwright:ms-playwright" \
            --name "WebImageSaver" app.py

      - name: Zip artifact (macOS x64)
        run: |
          cd dist && zip -r ../WebImageSaver-mac-x64.zip WebImageSaver.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebImageSaver-mac-x64.zip
          path: WebImageSaver-mac-x64.zip
